language: python
services:
  - redis-server
  - mongodb
  - rabbitmq
before_install:
  - sudo apt-get -q update
  - sudo apt-get -q build-dep python-scipy
  - sudo apt-get install -qq python-scipy
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r test-requirements.txt --use-mirrors
  - pip install -q $DJANGO
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
  - "django-admin.py version;"
  - "flake8 --exclude=migrations --ignore=E501,F403,F401 --statistics recommends;"
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
script: python recommends/tests/runtests.py
after_failure:
  - env
  - cat $PYTHONPATH
